version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./demo-small-20170815.sql:/docker-entrypoint-initdb.d/init.sql   # it's slow :(
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    # container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"